package kvraft

const (
	OK             = "OK"
	ErrNoKey       = "ErrNoKey"
	ErrWrongLeader = "ErrWrongLeader"
)

type Err string

// Put or Append
type PutAppendArgs struct {
	Key   string
	Value string
	Op    string // "Put" or "Append"

	// You'll have to add definitions here.
	OpID int64 // generated by client.go using nrand()
}

type PutAppendReply struct {
	Err Err
}

type GetArgs struct {
	Key string

	// You'll have to add definitions here.
	OpID int64 // generated by client.go using nrand()
}

type GetReply struct {
	Err   Err
	Value string
}
